// Code generated by MockGen. DO NOT EDIT.
// Source: /home/tetra/github-repos/auth-go/Session-based/internal/api/middleware/middleware.go
//
// Generated by this command:
//
//	mockgen -source /home/tetra/github-repos/auth-go/Session-based/internal/api/middleware/middleware.go -destination /home/tetra/github-repos/auth-go/Session-based/internal/api/middleware/mock/middleware_mosk.go -package middlemocks
//

// Package middlemocks is a generated GoMock package.
package middlemocks

import (
	context "context"
	reflect "reflect"
	models "sessions-based/internal/domain/models"

	gomock "go.uber.org/mock/gomock"
)

// MockAuthService is a mock of AuthService interface.
type MockAuthService struct {
	ctrl     *gomock.Controller
	recorder *MockAuthServiceMockRecorder
	isgomock struct{}
}

// MockAuthServiceMockRecorder is the mock recorder for MockAuthService.
type MockAuthServiceMockRecorder struct {
	mock *MockAuthService
}

// NewMockAuthService creates a new mock instance.
func NewMockAuthService(ctrl *gomock.Controller) *MockAuthService {
	mock := &MockAuthService{ctrl: ctrl}
	mock.recorder = &MockAuthServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthService) EXPECT() *MockAuthServiceMockRecorder {
	return m.recorder
}

// GetSession mocks base method.
func (m *MockAuthService) GetSession(ctx context.Context, sessionID string) (*models.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSession", ctx, sessionID)
	ret0, _ := ret[0].(*models.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSession indicates an expected call of GetSession.
func (mr *MockAuthServiceMockRecorder) GetSession(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSession", reflect.TypeOf((*MockAuthService)(nil).GetSession), ctx, sessionID)
}
